# Generated by Django 5.0 on 2024-08-19 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMMENTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMENT', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COURSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUBLICATION_DATE', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('COURSE_NAME', models.CharField(max_length=500, unique=True)),
                ('COVER_PHOTO', models.ImageField(upload_to='images/')),
                ('RATING', models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('1', '1'), ('5', '5'), ('3', '3')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LECTURES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=500)),
                ('VIDEO', models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mkv', 'mp3', 'mp4'])])),
                ('ADDITIONAL_FILES', models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
            ],
        ),
        migrations.CreateModel(
            name='REVIEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPINION', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
