# Generated by Django 5.0 on 2024-08-30 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMMENTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WRITING_DATE', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('COMMENT', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COURSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUBLICATION_DATE', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('COURSE_NAME', models.CharField(max_length=500, unique=True)),
                ('COVER_PHOTO', models.ImageField(upload_to='images/')),
                ('IsDraft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LECTURES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=500)),
                ('VIDEO', models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mkv', 'mp3', 'mp4'])])),
                ('ADDITIONAL_FILES', models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATING', models.IntegerField(blank=True, choices=[(2, '2'), (4, '4'), (1, '1'), (5, '5'), (3, '3')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REVIEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WRITING_DATE', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('OPINION', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'ordering': ['-WRITING_DATE'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['TimeStamp'],
            },
        ),
    ]
