# Generated by Django 5.0 on 2024-08-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HOME_AREA', '0001_initial'),
        ('INSTRUCTOR', '0001_initial'),
        ('STUDENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='USER_NAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student'),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruct', to='INSTRUCTOR.instructor'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='courseRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME_AREA.courses'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='HOME_AREA.courses'),
        ),
        migrations.AddField(
            model_name='comments',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME_AREA.lectures'),
        ),
        migrations.AddField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME_AREA.courses'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='USER_NAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOME_AREA.courses'),
        ),
    ]
