# Generated by Django 5.0 on 2024-08-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_AREA', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='HOME_AREA.courses'),
        ),
    ]
