# Generated by Django 5.0 on 2024-08-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_AREA', '0003_alter_lectures_course'),
        ('INSTRUCTOR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruct', to='INSTRUCTOR.instructor'),
        ),
    ]
