# Generated by Django 5.0 on 2024-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_AREA', '0004_alter_courses_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='IsDraft',
            field=models.BooleanField(default=False),
        ),
    ]
