# Generated by Django 5.0 on 2024-08-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_AREA', '0005_courses_isdraft'),
        ('STUDENT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='USER_NAME',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student'),
        ),
    ]
