# Generated by Django 5.0 on 2024-08-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_AREA', '0007_alter_reviews_options_comments_writing_date_and_more'),
        ('STUDENT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='RATING',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='USER_NAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATING', models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('1', '1'), ('5', '5'), ('3', '3')], max_length=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME_AREA.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT.student')),
            ],
        ),
    ]
