# Generated by Django 5.0 on 2024-08-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT', '0002_student_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('ENROLL', 'LEAVE_REVIEW')], 'verbose_name_plural': 'Students'},
        ),
    ]
