# Generated by Django 5.0 on 2024-08-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTRUCTOR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
